### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by javakam** [lecoler/md-list#1]
目录的位置和insight的目录重叠了, 建议放到右面.要是能悬浮就更好了

**Comment by lecoler** [comment]
悬浮没问题，下一个版本更新，感谢反馈 @javakam

**Comment by javakam** [comment]
上午也弄了一个目录效果🐶 [https://www.cnblogs.com/jooy/p/11724077.html](https://www.cnblogs.com/jooy/p/11724077.html)

**Comment by lecoler** [comment]
@javakam 已更新至1.0版本，有问题请随时反馈，谢谢！
